services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=precious
      - POSTGRES_PASSWORD=tasks1234
      - POSTGRES_DB=tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
